# Book settings
title:
author: World Bank Development Data Group
logo: docs/images/logo.png

repository:
    url: https://github.com/luisesanmartin/mock-repo
    branch: main

html:
    home_page_in_navbar: false
    extra_navbar: ""
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    baseurl: https://luisesanmartin.github.io/mock-repo

only_build_toc_files: true
